### ISSUE TITLE
Achievement Popups Stop Working

### ISSUE THREAD

**Issue by BoDDEneR** [SteamAchievementNotifier/SteamAchievementNotifier#42]
Hi! First of all: Thank you for your work!

I have similar problem as #20 this issue.
I already switched to beta version, and couple of days app was working fine.

Later pop-ups has stopped showing about 10 hours of app working and switching games.
Now it can stop around a hour later.

I don't turn off PC by night, so app is always on. I can get working pop-ups if I reload app after every game session, but honestly, it not worth it.

I just can't understand what going wrong and why it happens.
Any tips? I really in love with you app ^_^

Log file from console (around 30 minutes has pass after app was launched + get an achievement in game)

```
DEBUG: "checksteamdetails" CRON job starting...
san1.8.js:4285 Steam is running.
san1.8.js:3306 DEBUG: "checksteamdetails" CRON job stopped
san1.8.js:3394 Steam3ID (For user logged into Steam client): 38393360
san1.8.js:3396 Steam installation path: c:/program files (x86)/steam
san1.8.js:3433 DEBUG: "sanidle" CRON job starting...
san1.8.js:592 Rare Test Notification added to queue.
san1.8.js:709 Queue is empty.
san1.8.js:3492 DEBUG: "sanidle" CRON job stopped
san1.8.js:3544 AppID 261550 has achievements (50)
san1.8.js:3995 Tracking changes to file: c:/program files (x86)/steam/appcache/stats/UserGameStats_38393360_261550.bin
san1.8.js:4006 DEBUG: "checkgame" CRON job starting...
san1.8.js:3449 Now tracking achievements for: Mount & Blade II: Bannerlord
san1.8.js:3334 Using URL: https://steamcommunity.com/profiles/76561197998659088/stats/261550/?xml=1
san1.8.js:4012 DEBUG: "checkgame" CRON job stopped [AppID is 0]
san1.8.js:3394 Steam3ID (For user logged into Steam client): 38393360
san1.8.js:3396 Steam installation path: c:/program files (x86)/steam
san1.8.js:3433 DEBUG: "sanidle" CRON job starting...
san1.8.js:3492 DEBUG: "sanidle" CRON job stopped
san1.8.js:3523 local.json is empty
san1.8.js:3544 AppID 261550 has achievements (50)
san1.8.js:3995 Tracking changes to file: c:/program files (x86)/steam/appcache/stats/UserGameStats_38393360_261550.bin
san1.8.js:4006 DEBUG: "checkgame" CRON job starting...
san1.8.js:3449 Now tracking achievements for: Mount & Blade II: Bannerlord
san1.8.js:3334 Using URL: https://steamcommunity.com/profiles/76561197998659088/stats/261550/?xml=1
san1.8.js:4012 DEBUG: "checkgame" CRON job stopped [AppID is 0]
san1.8.js:3394 Steam3ID (For user logged into Steam client): 38393360
san1.8.js:3396 Steam installation path: c:/program files (x86)/steam
san1.8.js:3433 DEBUG: "sanidle" CRON job starting...
san1.8.js:3492 DEBUG: "sanidle" CRON job stopped
san1.8.js:3523 local.json is empty
san1.8.js:3544 AppID 261550 has achievements (50)
san1.8.js:3995 Tracking changes to file: c:/program files (x86)/steam/appcache/stats/UserGameStats_38393360_261550.bin
san1.8.js:4006 DEBUG: "checkgame" CRON job starting...
san1.8.js:3449 Now tracking achievements for: Mount & Blade II: Bannerlord
san1.8.js:3334 Using URL: https://steamcommunity.com/profiles/76561197998659088/stats/261550/?xml=1
san1.8.js:4012 DEBUG: "checkgame" CRON job stopped [AppID is 0]
san1.8.js:3394 Steam3ID (For user logged into Steam client): 38393360
san1.8.js:3396 Steam installation path: c:/program files (x86)/steam
san1.8.js:3433 DEBUG: "sanidle" CRON job starting...
san1.8.js:3492 DEBUG: "sanidle" CRON job stopped
san1.8.js:3523 local.json is empty
san1.8.js:3544 AppID 261550 has achievements (50)
san1.8.js:3995 Tracking changes to file: c:/program files (x86)/steam/appcache/stats/UserGameStats_38393360_261550.bin
san1.8.js:4006 DEBUG: "checkgame" CRON job starting...
san1.8.js:3449 Now tracking achievements for: Mount & Blade II: Bannerlord
san1.8.js:3334 Using URL: https://steamcommunity.com/profiles/76561197998659088/stats/261550/?xml=1
san1.8.js:4012 DEBUG: "checkgame" CRON job stopped [AppID is 0]
san1.8.js:3394 Steam3ID (For user logged into Steam client): 38393360
san1.8.js:3396 Steam installation path: c:/program files (x86)/steam
san1.8.js:3433 DEBUG: "sanidle" CRON job starting...
san1.8.js:3492 DEBUG: "sanidle" CRON job stopped
san1.8.js:3523 local.json is empty
san1.8.js:3544 AppID 261550 has achievements (50)
san1.8.js:3995 Tracking changes to file: c:/program files (x86)/steam/appcache/stats/UserGameStats_38393360_261550.bin
san1.8.js:4006 DEBUG: "checkgame" CRON job starting...
san1.8.js:3449 Now tracking achievements for: Mount & Blade II: Bannerlord
san1.8.js:3334 Using URL: https://steamcommunity.com/profiles/76561197998659088/stats/261550/?xml=1
san1.8.js:4035 File was changed!
san1.8.js:4039 DEBUG: "checkgame" CRON job stopped [Checking achievement info...]
san1.8.js:3544 AppID 261550 has achievements (50)
san1.8.js:3995 Tracking changes to file: c:/program files (x86)/steam/appcache/stats/UserGameStats_38393360_261550.bin
san1.8.js:4006 DEBUG: "checkgame" CRON job starting...
san1.8.js:3334 Using URL: https://steamcommunity.com/profiles/76561197998659088/stats/261550/?xml=1
san1.8.js:4035 File was changed!
san1.8.js:4039 DEBUG: "checkgame" CRON job stopped [Checking achievement info...]
san1.8.js:3544 AppID 261550 has achievements (50)
san1.8.js:3995 Tracking changes to file: c:/program files (x86)/steam/appcache/stats/UserGameStats_38393360_261550.bin
san1.8.js:4006 DEBUG: "checkgame" CRON job starting...
san1.8.js:3334 Using URL: https://steamcommunity.com/profiles/76561197998659088/stats/261550/?xml=1
san1.8.js:4035 File was changed!
san1.8.js:4039 DEBUG: "checkgame" CRON job stopped [Checking achievement info...]
san1.8.js:3609 Main Notification added to queue.
san1.8.js:3544 AppID 261550 has achievements (50)
san1.8.js:3995 Tracking changes to file: c:/program files (x86)/steam/appcache/stats/UserGameStats_38393360_261550.bin
san1.8.js:4006 DEBUG: "checkgame" CRON job starting...
san1.8.js:3334 Using URL: https://steamcommunity.com/profiles/76561197998659088/stats/261550/?xml=1
san1.8.js:3939 Game has not yet been completed
san1.8.js:451 Main Test Notification added to queue.
```

**Comment by SteamAchievementNotifier** [comment]
Hey @BoDDEneR,

I've had quite a few reports of similar behaviour recently, and I'm working on a new method of achievement tracking which will be included in the next upcoming

**Comment by SteamAchievementNotifier** [comment]
Hey @BoDDEneR,

I've had quite a few reports of similar behaviour recently, and I'm working on a new method of achievement tracking which will be included in the next upcoming release (V1.85). As the next version is being re-written from the ground up, I haven't got an ETA on when this will be released, but I'm planning to release some sort of "open Alpha", and I would be interested to know whether the issue still occurs.

I'll let you know when I'm able to provide any kind of update to this.

Thanks!

**Comment by SteamAchievementNotifier** [comment]
Hey @BoDDEneR,

The Alpha release of version 1.85 has now been released, and is available for testing here: https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/releases/tag/1.85

Obviously, due to being an Alpha, there are issues with it, but I would be interested to know whether the tracking issue is now resolved if you wanted to give it a try.

Thanks!

**Comment by BoDDEneR** [comment]
> Hey @BoDDEneR,
> 
> The Alpha release of version 1.85 has now been released, and is available for testing here: https://github.com/SteamAchievementNotifier/SteamAchievementNotifier/releases/tag/1.85
> 
Thank you for the reminder! 

I will test latest update and will come back with feedback around 1-2 days😊

**Comment by BoDDEneR** [comment]
@SteamAchievementNotifier 

First of all — great work on new update! UI looks really neat, modern and have a lot of functionality. This is really an accomplishment!

As for the achivements — i don't know if it intended, but game detection breaks, if you launch a game with no achivements (RimWorld for excample). After changin the game — detection no longer works, and notification about achivements too, obviosly.
```
[31.07.2023, 19:21:11][INFO]:
"config" loaded successfully
[31.07.2023, 19:21:11][INFO]:
"accounts" loaded successfully
[31.07.2023, 19:21:22][INFO]:
Starting SAN!
[31.07.2023, 19:21:22][INFO]:
SAN user matches Steam client user
[31.07.2023, 19:21:22][ERROR]:
Error caching achievement data: Unable to access achievement data for 294100
```
For the second time i launch RimWorld i saw a error notification, and if you don't forget restart an app — everything seems to be working fine.

Is there a possibility to prevent a break of game detection? Or create some form of list Steam app ID, which will help an app to ignore specific apps?

**Comment by SteamAchievementNotifier** [comment]
Hey again @BoDDEneR,

Glad to hear that you like the new design! I'm a lot happier with it now.

But yes, handling games with no achievements was something I must have missed as I did include a check for this in the old version. I'll review it for the next update, but thanks for bringing it to my attention 👍

**Comment by SteamAchievementNotifier** [comment]
Hey again @BoDDEneR,

I've pushed an update to V1.85.3 which should resolve the issue with launching games with no achievements. Let me know if it's working for you.

Thanks!

**Comment by BoDDEneR** [comment]
Hi @SteamAchievementNotifier !

Sadly, but update didn't help me and games still stop detecting after launching game with no steam achievements.
There are no difference whatsoever with previous update - still the same.
I did clean reinstall and this was no help either 😔

Here is one of the logs:

```
[11.08.2023, 19:08:44][INFO]:
"config" loaded successfully
[11.08.2023, 19:08:44][INFO]:
"accounts" loaded successfully
[11.08.2023, 19:09:55][INFO]:
Account for "DEneR" (76561197998659088) already exists in "accounts"!
[11.08.2023, 19:11:36][INFO]:
Starting SAN!
[11.08.2023, 19:11:36][INFO]:
SAN user matches Steam client user
[11.08.2023, 19:11:41][INFO]:
Tracking changes to file: c:/program files (x86)/steam/appcache/stats/UserGameStats_38393360_610360.bin
[11.08.2023, 19:11:44][INFO]:
MSG: File has been modified - Checking achievement progress...
APPID: 610360
[11.08.2023, 19:11:45][INFO]:
Re-checking unlock status for APPID: 610360
[11.08.2023, 19:11:46][INFO]:
Final re-check of unlock status for APPID: 610360
[11.08.2023, 19:11:51][INFO]:
AppID is 0
[11.08.2023, 19:13:18][INFO]:
Starting SAN!
[11.08.2023, 19:13:18][INFO]:
SAN user matches Steam client user
[11.08.2023, 19:13:18][ERROR]:
Error caching achievement data: Unable to access achievement data for 294100
```

**Comment by SteamAchievementNotifier** [comment]
Hey again @BoDDEneR,

I've just pushed an update for V1.85.4 which again attempts to address this issue. Could you let me know if it's working with games that have no achievements after updating?

Thanks!

**Comment by BoDDEneR** [comment]
Hi @SteamAchievementNotifier 

I was testing new update for a day now and seems everything working smoothly 🙂

You my hero, thank you for your work!

**Comment by SteamAchievementNotifier** [comment]
Hey again @BoDDEneR,

Excellent, glad to hear it! I'll close this for now, but feel free to open another issue if you have any more problems with it, and thanks again for bringing it to my attention!

Thanks!
